/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sebas
 */
public class Bienvenida extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEntrar1 = new javax.swing.JButton();
        btnEntrar2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Bradley Hand ITC", 3, 36)); // NOI18N
        jLabel2.setText("BIENVENIDO ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 60, 460, 80);

        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 3, 24)); // NOI18N
        jLabel1.setText("¿Que desea hacer?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 190, 240, 20);

        jLabel6.setFont(new java.awt.Font("Bradley Hand ITC", 3, 24)); // NOI18N
        jLabel6.setText("Seleccione una opcion");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 370, 270, 25);

        btnEntrar1.setBackground(new java.awt.Color(0, 0, 0));
        btnEntrar1.setFont(new java.awt.Font("Bradley Hand ITC", 3, 18)); // NOI18N
        btnEntrar1.setForeground(new java.awt.Color(204, 204, 204));
        btnEntrar1.setText("2/Cargar Partida");
        btnEntrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrar1MouseClicked(evt);
            }
        });
        btnEntrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar1);
        btnEntrar1.setBounds(690, 270, 190, 33);

        btnEntrar2.setBackground(new java.awt.Color(0, 0, 0));
        btnEntrar2.setFont(new java.awt.Font("Bradley Hand ITC", 3, 18)); // NOI18N
        btnEntrar2.setForeground(new java.awt.Color(204, 204, 204));
        btnEntrar2.setText("1/ Crear partida");
        btnEntrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrar2MouseClicked(evt);
            }
        });
        btnEntrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar2);
        btnEntrar2.setBounds(410, 270, 180, 33);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/8103864711_a6a58b11c7_z.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, -230, 1000, 960);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrar1MouseClicked

     

    }//GEN-LAST:event_btnEntrar1MouseClicked

    private void btnEntrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrar1ActionPerformed

    private void btnEntrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrar2MouseClicked

    private void btnEntrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar1;
    private javax.swing.JButton btnEntrar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
