
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sebas
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        btnEntrar1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Bradley Hand ITC", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("BIENVENIDO A REGISTRO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 80, 550, 40);

        jLabel6.setFont(new java.awt.Font("Bradley Hand ITC", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Por favor digite los siguientes datos:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 160, 358, 29);

        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Nombre: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 230, 75, 30);

        jLabel2.setFont(new java.awt.Font("Bradley Hand ITC", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Apellido:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 290, 72, 24);

        jLabel3.setFont(new java.awt.Font("Bradley Hand ITC", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Correo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 340, 56, 24);

        jLabel4.setFont(new java.awt.Font("Bradley Hand ITC", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 400, 100, 24);

        jLabel5.setFont(new java.awt.Font("Bradley Hand ITC", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Confirmar Contraseña:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 460, 195, 24);

        jTextField2.setFont(new java.awt.Font("Bradley Hand ITC", 3, 18)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(410, 220, 243, 30);

        jTextField1.setFont(new java.awt.Font("Bradley Hand ITC", 3, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(410, 280, 243, 30);

        jTextField6.setFont(new java.awt.Font("Bradley Hand ITC", 3, 18)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(410, 340, 244, 30);

        jPasswordField1.setFont(new java.awt.Font("Bradley Hand ITC", 3, 18)); // NOI18N
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(410, 400, 243, 30);

        jPasswordField2.setFont(new java.awt.Font("Bradley Hand ITC", 3, 18)); // NOI18N
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(410, 460, 243, 30);

        btnEntrar1.setBackground(new java.awt.Color(0, 0, 0));
        btnEntrar1.setFont(new java.awt.Font("Bradley Hand ITC", 3, 18)); // NOI18N
        btnEntrar1.setForeground(new java.awt.Color(204, 204, 204));
        btnEntrar1.setText("Registrarse");
        btnEntrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrar1MouseClicked(evt);
            }
        });
        btnEntrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar1);
        btnEntrar1.setBounds(320, 560, 166, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/casa-abandonada-copy.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-490, -220, 1370, 960);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnEntrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrar1MouseClicked

      JOptionPane.showMessageDialog(this, "Usuario Registrado"); 
      Bienvenida BN= new Bienvenida();
      BN.setVisible(true); 
      dispose();

    }//GEN-LAST:event_btnEntrar1MouseClicked

    private void btnEntrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
